test('verifyPassword, with a failing rule, returns error based on rule.reason', () => {
  // ...
});

describe('verifyPassword', () => {
  describe('with a failing rule', () => {
    it('returns error based on the rule.reason', () => {
      // ...
    });
  });
});
